"""
Feasts that relax an SPC fast, by fixed (Julian) month and day.

Generated by scripts/serbian/derive_spc_fasting.py from
data/processed/sr/pravoslavno_fasting.json (pravoslavno.rs, "Календар поста").
Do not edit by hand: re-scrape and re-run the script. A day takes its
feast's level only when that is more permissive than its own, so an entry
never imposes a fast; the names are the SPC calendar's own notes.
"""

SPC_RELAXATIONS = {
    (1, 6): "free",  # Богојављање (4 obs)
    (1, 7): "fish",  # Јовањдан (2 obs)
    (1, 14): "fish",  # Свети Сава (2 obs)
    (1, 16): "hotWithOil",  # Часне вериге (3 obs)
    (1, 18): "hotWithOil",  # Св. Атанасије Велики (3 obs)
    (1, 30): "fish",  # Света Три Јерарха (2 obs)
    (2, 1): "hotWithOil",  # Св. Трифун (2 obs)
    (2, 2): "hotWithOil",  # Сретење Господње (1 obs)
    (2, 3): "hotWithOil",  # Св. Симеон и Ана (2 obs)
    (2, 10): "hotWithOil",  # Св. Харалампије (1 obs)
    (3, 9): "hotWithOil",  # Младенци (6 obs)
    (3, 25): "hotWithOil",  # Благовести (7 obs)
    (6, 15): "fish",  # Видовдан (8 obs)
    (6, 24): "fish",  # Ивањдан (10 obs)
    (6, 29): "hotWithOil",  # Петровдан Петровдан (3 obs)
    (7, 1): "hotWithOil",  # Св. Козма и Дамјан (4 obs)
    (7, 8): "hotWithOil",  # Св. Прокопије (4 obs)
    (7, 13): "hotWithOil",  # Сабор арх. Гаврила (3 obs)
    (7, 15): "hotWithOil",  # Св. Кирик и Јулита (4 obs)
    (7, 17): "hotWithOil",  # Огњена Марија (5 obs)
    (7, 20): "hotWithOil",  # Илиндан (3 obs)
    (7, 22): "hotWithOil",  # Блага Марија (4 obs)
    (7, 26): "hotWithOil",  # Св. Параскева (5 obs)
    (7, 27): "hotWithOil",  # Св. Пантелејмон (3 obs)
    (8, 6): "fish",  # Преображење (9 obs)
    (8, 15): "fish",  # (3 obs)
    (8, 22): "hotWithOil",  # Св. Агатоник (3 obs)
    (8, 26): "hotWithOil",  # Св. Адријан и Наталија (4 obs)
    (8, 30): "hotWithOil",  # Пренос моштију А. Невског (5 obs)
    (9, 1): "hotWithOil",  # Симеон Столпник (3 obs)
    (9, 9): "hotWithOil",  # Св. Јоаким и Ана (4 obs)
    (9, 17): "hotWithOil",  # Св. Вера, Нада, Љубав и Софија (3 obs)
    (9, 20): "hotWithOil",  # Св. Јевстатије (5 obs)
    (9, 23): "hotWithOil",  # Зачеће Св. Јована (4 obs)
    (9, 26): "hotWithOil",  # Св. Јован Богослов (3 obs)
    (9, 29): "hotWithOil",  # Михољдан (3 obs)
    (10, 1): "hotWithOil",  # Покров Пресвете Богородице (3 obs)
    (10, 6): "hotWithOil",  # Томиндан (3 obs)
    (10, 7): "hotWithOil",  # Срђевдан (4 obs)
    (10, 14): "hotWithOil",  # Света Петка (4 obs)
    (10, 18): "hotWithOil",  # Св. Лука (5 obs)
    (11, 16): "hotWithOil",  # Апостол Матеј (3 obs)
    (11, 21): "fish",  # Ваведење (10 obs)
    (11, 24): "hotWithOil",  # Св. Екатарина (3 obs)
    (11, 25): "hotWithOil",  # Св. Климент (4 obs)
    (11, 26): "hotWithOil",  # Св. Алемпије Столпник (3 obs)
    (11, 30): "hotWithOil",  # Св. Андреј Првозвани (3 obs)
    (12, 4): "hotWithOil",  # Св. Варвара (5 obs)
    (12, 5): "hotWithOil",  # Св. Сава Освећени (3 obs)
    (12, 6): "fish",  # Св. Никола (9 obs)
    (12, 9): "hotWithOil",  # Зачеће Св. Ане (4 obs)
    (12, 12): "hotWithOil",  # Св. Спиридон (3 obs)
    (12, 20): "hotWithOil",  # Св. Игњатије Богоносац (10 obs)
}

# The feasts that also lift a day of Great Lent. Every other feast relaxes an
# ordinary Wednesday or Friday, or a day of another fast, but not Lent.
SPC_LENT_FEASTS = {(3, 9), (3, 25)}
