#!/usr/bin/env python3
"""Bundle the Russian name days for the app: OrthodoxCalendar/Localization/imeniny_ru.json.

Reads data/processed/ru/imeniny.json (generated by build_imeniny.py from the
azbyka.ru API) and data/processed/ru/imeniny_civil_names.json (hand-curated)
and writes only what the app reads, compact:

  days     church (Julian) MM-DD -> "main,main;other,other" — the day's
           "Именины сегодня" names, main saints (p=1) before the semicolon.
           St John Cassian's day is "02-29": the app shows it with the 28th in
           a year without a Julian February 29, as the Church does.
  pascha   distance from Pascha -> the same string, for the Pascha-bound days
  rules    commemorations kept on a weekday inside a window of church dates
           ("the Sunday after the Nativity"); each is {"w": [[weekday, first,
           last], ...], "n": "names"}, weekday 0 = Monday … 6 = Sunday — the
           fixed_cycle.between() form, checked below against 2026's placement
  titles   every commemoration title once
  names    church name -> [[anchor, title index, new martyr 0/1], ...], sorted
           by date: anchor "MM-DD", "P<n>" (from Pascha) or "R<i>" (rules[i]).
           Every commemoration of a saint of that name — the app picks the
           first on/after a birthday and offers the rest to choose from.
  civil    folded civil or diminutive form -> church forms, usual first

Civil mappings the curators marked `_unsure` are left out unless their note
attributes them to azbyka.ru itself (its nameLib widget or its "Пояснения к
определителю именин"), and Юрий -> Георгий is kept by decision. A left-out name
still works when it is itself a church name (Маргарита, Виктория).

Usage: python3 scripts/russian/bundle_imeniny.py [--out FILE]
"""
import argparse
import json
import os
import sys
from datetime import date, timedelta

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "data", "processed", "ru", "imeniny.json")
CIVIL = os.path.join(ROOT, "data", "processed", "ru", "imeniny_civil_names.json")
OUT = os.path.join(ROOT, "OrthodoxCalendar", "Localization", "imeniny_ru.json")

SATURDAY, SUNDAY, MONDAY = 5, 6, 0

# The printed rules of the moving commemorations, as fixed_cycle.MOVED places
# the same entries in the calendar (each checked there against
# days.pravoslavie.ru 2021-2026). With the Nativity on a Sunday there is no
# Sunday in its octave, and Joseph, David and James are kept on 26 December.
RULES = {
    "Неделя по Рождестве Христовом": [(SUNDAY, "12-26", "12-31"), (MONDAY, "12-26", "12-26")],
    "переходящее празднование в субботу по Богоявлении": [(SATURDAY, "01-07", "01-13")],
    "переходящее празднование в 1-е воскресенье после 10 июля": [(SUNDAY, "06-27", "07-03")],
    "переходящее празднование в 1-е воскресенье после 12 июля": [(SUNDAY, "06-30", "07-06")],
    "переходящее празднование в воскресенье перед 19 сентября": [(SUNDAY, "08-31", "09-06")],
}

# `_unsure` civil names kept although their note does not credit azbyka.ru.
KEEP_UNSURE = {"Юрий"}


def azbyka_attributed(note: str) -> bool:
    return "azbyka" in note.lower()


def fold(name: str) -> str:
    return name.strip().lower().replace("ё", "е")


def julian_to_civil(year: int, key: str) -> date:
    m, d = int(key[:2]), int(key[3:])
    if (m, d) == (2, 29) and year % 4:
        d = 28
    return date(year, m, d) + timedelta(days=13)


def rule_dates_2026(windows) -> list:
    """Church MM-DD of every date the rule gives whose civil date is in 2026."""
    out = []
    for jy in (2025, 2026):
        for wd, first, last in windows:
            m, d = int(first[:2]), int(first[3:])
            cur = date(jy, m, d)
            end = date(jy, int(last[:2]), int(last[3:]))
            while cur <= end:
                civil = cur + timedelta(days=13)
                if civil.weekday() == wd and civil.year == 2026:
                    out.append(cur.strftime("%m-%d"))
                cur += timedelta(days=1)
    return out


def day_string(entries) -> str:
    """"main,main;other" with each name once, keeping the day's own order."""
    seen, main, other = set(), [], []
    for e in entries:
        if e["name"] in seen:
            continue
        seen.add(e["name"])
        (main if e.get("p", 2) == 1 else other).append(e["name"])
    return ",".join(main) + ";" + ",".join(other)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=OUT)
    args = ap.parse_args()

    src = json.load(open(SRC, encoding="utf-8"))
    civil_src = json.load(open(CIVIL, encoding="utf-8"))
    by_name = src["byName"]

    # ── days: St Cassian (leapYearDate 02-29) moves to his own day ──
    days = {}
    leap = []
    for key, entries in src["byDate"].items():
        keep = []
        for e in entries:
            if e.get("leapYearDate"):
                leap.append((e["leapYearDate"], e))
            else:
                keep.append(e)
        days[key] = keep
    for key, e in leap:
        days.setdefault(key, []).append(e)
    days = {k: day_string(v) for k, v in sorted(days.items()) if v}

    pascha = {k: day_string(v) for k, v in sorted(src["byPascha"].items(), key=lambda kv: int(kv[0]))}

    # ── rules ──
    rules, rule_index = [], {}
    for m in src["moving"]:
        windows = RULES.get(m["rule"])
        if windows is None:
            sys.exit(f"bundle_imeniny: no rule form for {m['rule']!r} ({m['name']})")
        got = rule_dates_2026(windows)
        if m["date2026"] not in got:
            sys.exit(f"bundle_imeniny: {m['rule']!r} gives {got} in 2026, the source says {m['date2026']}")
        if m["rule"] not in rule_index:
            rule_index[m["rule"]] = len(rules)
            rules.append({"w": [list(w) for w in windows], "names": []})
        names = rules[rule_index[m["rule"]]]["names"]
        if m["name"] not in names:
            names.append(m["name"])
    rules_out = [{"w": r["w"], "n": ",".join(r["names"])} for r in rules]

    # ── names ──
    titles, title_index = [], {}
    names_out = {}
    for name in sorted(by_name):
        rows = []
        seen = set()
        for e in by_name[name]:
            if "rule" in e:
                anchor = f"R{rule_index[e['rule']]}"
            elif "pascha" in e:
                anchor = f"P{e['pascha']}"
            else:
                anchor = e.get("leapYearDate") or e["date"]
            t = e["title"]
            if t not in title_index:
                title_index[t] = len(titles)
                titles.append(t)
            key = (anchor, title_index[t])
            if key in seen:
                continue
            seen.add(key)
            rows.append([anchor, title_index[t], 1 if e.get("newmartyr") else 0])
        names_out[name] = rows

    # ── civil names ──
    unsure = civil_src.get("_unsure", {})
    excluded = sorted(n for n, note in unsure.items()
                      if n not in KEEP_UNSURE and not azbyka_attributed(note))
    kept_unsure = sorted(n for n in unsure if n not in excluded)
    civil = {}
    for table in ("male", "female"):
        for civ, forms in civil_src[table].items():
            if civ in excluded:
                continue
            forms = [f for f in forms if f in by_name]
            if forms:
                civil.setdefault(fold(civ), [])
                civil[fold(civ)] += [f for f in forms if f not in civil[fold(civ)]]
    for dim, full in civil_src.get("diminutives", {}).items():
        target = civil.get(fold(full)) or ([full] if full in by_name else None)
        if target and fold(dim) not in civil:
            civil[fold(dim)] = list(target)

    out = {
        "_note": "Generated by scripts/russian/bundle_imeniny.py from data/processed/ru/imeniny*.json. Do not edit by hand.",
        "days": days, "pascha": pascha, "rules": rules_out,
        "titles": titles, "names": names_out, "civil": dict(sorted(civil.items())),
    }
    with open(args.out, "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, separators=(",", ":"))
    size = os.path.getsize(args.out)
    print(f"{args.out}: {size / 1024:.0f} KB — {len(days)} days, {len(pascha)} Pascha days, "
          f"{len(rules_out)} rules, {len(names_out)} names, {len(titles)} titles, {len(civil)} civil forms")
    print(f"unsure civil names excluded: {', '.join(excluded)}")
    print(f"unsure civil names kept: {', '.join(kept_unsure)}")


if __name__ == "__main__":
    main()
