#!/usr/bin/env python3
"""
Derive the SPC feast relaxations (scripts/shared/spc_fasting_relaxations.py)
from the SPC's own fasting calendar.

The engine's SPC rules give each day its period's level — water on a strict
day, oil or fish on the weekends of the fasts. Which feasts lift a fast, and how
far (St Nicholas to fish in the Nativity Fast, St Agathonicus to oil on a
Friday), is data rather than a rule: nothing in the saints data predicts it. This
finds every day in data/processed/sr/pravoslavno_fasting.json where the SPC
calendar allows more than the period level, and groups them by the fixed
(Julian) date they fall on.

Usage:
  python3 scripts/serbian/derive_spc_fasting.py              write the table
  python3 scripts/serbian/derive_spc_fasting.py --holdout Y  derive without year Y,
      then report how well that table predicts Y: the honest measure of a year
      nobody has scraped.
"""
import collections, os, sys
from datetime import date

HERE = os.path.dirname(__file__)
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "..", "shared"))
from pravoslavno_levels import load_fixture, pravoslavno_level  # noqa: E402
from paschalion import Paschalion  # noqa: E402
import fasting_engine as fe  # noqa: E402

OUT = os.path.join(HERE, "..", "shared", "spc_fasting_relaxations.py")
_P = {}


def pasch(year):
    if year not in _P:
        _P[year] = Paschalion(year)
    return _P[year]


def derive(fixture, exclude=()):
    """(table, conflicts, stricter).

    table: Julian date -> (level, lifts_lent, observations).
    conflicts: days this table *would* relax but the calendar held the period
        level — each a sign the table over-reaches.
    stricter: days the calendar is stricter than the rules — each a missing rule.
    """
    S = fe.STRICTNESS
    seen = collections.defaultdict(list)
    days = []
    stricter = []
    for ds, entry in sorted(fixture.items()):
        d = date.fromisoformat(ds)
        if d.year in exclude:
            continue
        p = pasch(d.year)
        base = fe.spc_fasting_level(d, p, relaxations={}, lent_feasts=set())
        truth = pravoslavno_level(entry)
        jmd, period = p.fixed_month_day(d), fe.spc_period(d, p)
        if S[truth] > S[base]:
            seen[jmd].append((ds, truth, entry.get("note"), period))
        elif S[truth] < S[base]:
            stricter.append((ds, base, truth, entry.get("note")))
        days.append((ds, jmd, base, truth, period))
    table = {}
    for jmd, obs in seen.items():
        levels = collections.Counter(t for _, t, _, _ in obs)
        table[jmd] = (levels.most_common(1)[0][0], any(per == "great_lent" for *_, per in obs), obs, dict(levels))
    conflicts = collections.defaultdict(list)
    for ds, jmd, base, truth, period in days:
        if jmd not in table or truth != base or base in (fe.FREE, fe.TOTAL_ABSTINENCE):
            continue
        level, lifts_lent, _, _ = table[jmd]
        if (period != "great_lent" or lifts_lent) and S[level] > S[base]:
            conflicts[jmd].append(f"{ds} {period} {base}")
    return table, conflicts, stricter


def tables(table):
    return ({k: v[0] for k, v in table.items()}, {k for k, v in table.items() if v[1]})


def score(fixture, table, years):
    rel, lent = tables(table)
    ok = n = 0
    misses = []
    for ds, entry in fixture.items():
        d = date.fromisoformat(ds)
        if d.year not in years:
            continue
        got = fe.spc_fasting_level(d, pasch(d.year), relaxations=rel, lent_feasts=lent)
        want = pravoslavno_level(entry)
        n += 1
        if got == want:
            ok += 1
        else:
            misses.append((ds, want, got, entry.get("note")))
    return ok, n, misses


def write(table):
    lines = [
        '"""',
        "Feasts that relax an SPC fast, by fixed (Julian) month and day.",
        "",
        "Generated by scripts/serbian/derive_spc_fasting.py from",
        "data/processed/sr/pravoslavno_fasting.json (pravoslavno.rs, \"Календар поста\").",
        "Do not edit by hand: re-scrape and re-run the script. A day takes its",
        "feast's level only when that is more permissive than its own, so an entry",
        "never imposes a fast; the names are the SPC calendar's own notes.",
        '"""',
        "",
        "SPC_RELAXATIONS = {",
    ]
    for (jm, jd) in sorted(table):
        level, lifts_lent, obs, _ = table[(jm, jd)]
        notes = collections.Counter(n for _, _, n, _ in obs if n)
        name = notes.most_common(1)[0][0] if notes else ""
        lines.append(f'    ({jm}, {jd}): "{level}",  # ' + (f"{name} " if name else "") + f"({len(obs)} obs)")
    lines += ["}", "",
              "# The feasts that also lift a day of Great Lent. Every other feast relaxes an",
              "# ordinary Wednesday or Friday, or a day of another fast, but not Lent.",
              "SPC_LENT_FEASTS = {" + ", ".join(f"({jm}, {jd})" for (jm, jd) in sorted(table) if table[(jm, jd)][1]) + "}"]
    open(OUT, "w", encoding="utf-8").write("\n".join(lines) + "\n")


def main():
    fixture = load_fixture()
    years = sorted({int(k[:4]) for k in fixture})
    if "--holdout" in sys.argv:
        y = int(sys.argv[sys.argv.index("--holdout") + 1])
        table, _, _ = derive(fixture, exclude=(y,))
        ok, n, misses = score(fixture, table, {y})
        print(f"holdout {y}: table derived from the other {len(years) - 1} years predicts "
              f"{ok}/{n} = {100 * ok / n:.2f}%")
        for ds, want, got, note in misses:
            print(f"  {ds} {date.fromisoformat(ds):%a}: calendar {want}, engine {got}  {note or ''}")
        return
    table, conflicts, stricter = derive(fixture)
    write(table)
    print(f"{OUT}: {len(table)} feasts from {years[0]}-{years[-1]}")
    mixed = {k: v[3] for k, v in table.items() if len(v[3]) > 1}
    if mixed:
        print("\nfeasts relaxed to different levels in different years:", mixed)
    if conflicts:
        print("\nconflicts — the table would relax these, the calendar did not:")
        for jmd, held in sorted(conflicts.items()):
            print(f"  J{jmd[0]:02d}-{jmd[1]:02d} ({table[jmd][0]}): {held}")
    print(f"feasts that also lift Great Lent: {sorted(k for k, v in table.items() if v[1])}")
    if stricter:
        print(f"\n{len(stricter)} days the calendar is stricter than the rules (a missing rule each):")
        for ds, base, truth, note in stricter:
            print(f"  {ds} {date.fromisoformat(ds):%a}: rules {base}, calendar {truth}  {note or ''}")


if __name__ == "__main__":
    main()
